name: Publish 🔥

on:
  workflow_dispatch:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

env:
  AZURE_WEBAPP_NAME: DineEase
  AZURE_CONTAINER_REGISTRY: dineease.azurecr.io
  DOCKER_IMAGE_NAME_BACKEND: dineeasebackend
  DOCKER_IMAGE_NAME_FRONTEND: dineeasefrontend
  DOCKER_TAG: latest 

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1 
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }} 
          
      - name: Build and push Docker image for backend
        run: |
          docker build \
            --build-arg AZURE_STORAGE_ACCOUNT=${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --build-arg AZURE_STORAGE_ACCESS_KEY=${{ secrets.AZURE_STORAGE_ACCESS_KEY }} \
            --build-arg JWT_KEY=${{ secrets.JWT_KEY }} \
            --build-arg JWT_ISSUER=${{ secrets.JWT_ISSUER }} \
            --build-arg JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }} \
            --build-arg JWT_SUBJECT=${{ secrets.JWT_SUBJECT }} \
            --build-arg DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
            --build-arg GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} \
            -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_BACKEND }}:${{ env.DOCKER_TAG }} \
            -f ./BPR2-T2/Dockerfile \
            ./BPR2-T2
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_BACKEND }}:${{ env.DOCKER_TAG }}
          
      - name: Build and push Docker image for frontend
        run: |
          docker build \
            -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ env.DOCKER_TAG }} \
            -f ./BPR2-T1/Dockerfile \
            ./BPR2-T1
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ env.DOCKER_TAG }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: "${{ env.AZURE_WEBAPP_NAME }}"
          publish-profile: '${{ secrets.AZURE_PUBLISH_PROFILE }}'
          images: "${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_BACKEND }}:${{ env.DOCKER_TAG }}"

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with: 
          app-name: "${{ env.AZURE_WEBAPP_NAME }}"
          publish-profile: '${{ secrets.AZURE_PUBLISH_PROFILE }}'
          images: "${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_FRONTEND }}:${{ env.DOCKER_TAG }}"



