version: '3.9'

services:
  backend:
    image: "${AZURE_CONTAINER_REGISTRY}/${DOCKER_IMAGE_NAME_BACKEND}:${DOCKER_TAG}"
    container_name: backend
    ports:
      - "5000:5000" # Map container's backend port
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_SUBJECT=${JWT_SUBJECT}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

  frontend:
    image: "${AZURE_CONTAINER_REGISTRY}/${DOCKER_IMAGE_NAME_FRONTEND}:${DOCKER_TAG}"
    container_name: frontend
    ports:
      - "3000:3000" # Map container's frontend port
