version: '3'
services:
  backend:
    image: "${AZURE_CONTAINER_REGISTRY}/${DOCKER_IMAGE_NAME_BACKEND}:${DOCKER_TAG}"
    container_name: backend
    ports:
      - "8080:80" 
    env:
      - DB_CONNECTION=${DB_CONNECTION}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_SUBJECT=${JWT_SUBJECT}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
        AZURE_WEBAPP_NAME: DineEase
        AZURE_CONTAINER_REGISTRY: dineease.azurecr.io
        DOCKER_IMAGE_NAME_BACKEND: dineeasebackend
        DOCKER_IMAGE_NAME_FRONTEND: dineeasefrontend
        DOCKER_TAG: latest 
  frontend:
    image: "${AZURE_CONTAINER_REGISTRY}/${DOCKER_IMAGE_NAME_FRONTEND}:${DOCKER_TAG}"
    container_name: frontend
    ports:
      - "8081:80" 
